//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_Registry_Cleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Little_Registry_Cleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bug report could not be sent.
        /// </summary>
        internal static string crashReporterFail {
            get {
                return ResourceManager.GetString("crashReporterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent bug report successfully.
        /// </summary>
        internal static string crashReporterSuccess {
            get {
                return ResourceManager.GetString("crashReporterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added selected registry keys to the exclude list.
        /// </summary>
        internal static string mainAddExcludeEntry {
            get {
                return ResourceManager.GetString("mainAddExcludeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string mainAskExit {
            get {
                return ResourceManager.GetString("mainAskExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is freeware. If you paid for a copy of this program, get a refund!.
        /// </summary>
        internal static string mainFreeWareProgram {
            get {
                return ResourceManager.GetString("mainFreeWareProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Little Registry Cleaner.chm.
        /// </summary>
        internal static string mainInvalidHelpFile {
            get {
                return ResourceManager.GetString("mainInvalidHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to fix all selected problems?.
        /// </summary>
        internal static string mainProblemsFix {
            get {
                return ResourceManager.GetString("mainProblemsFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed problems from registry.
        /// </summary>
        internal static string mainProblemsRemoved {
            get {
                return ResourceManager.GetString("mainProblemsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted scanning the registry.
        /// </summary>
        internal static string mainScanningAborted {
            get {
                return ResourceManager.GetString("mainScanningAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished scanning the registry.
        /// </summary>
        internal static string mainScanningFinished {
            get {
                return ResourceManager.GetString("mainScanningFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a section to scan.
        /// </summary>
        internal static string mainSelectSections {
            get {
                return ResourceManager.GetString("mainSelectSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available. Would you like to download it?.
        /// </summary>
        internal static string mainUpdateAsk {
            get {
                return ResourceManager.GetString("mainUpdateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to exclude from the registry scan.
        /// </summary>
        internal static string optionsExcludeDir {
            get {
                return ResourceManager.GetString("optionsExcludeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry path cannot be empty.
        /// </summary>
        internal static string optionsExcludeEmptyRegPath {
            get {
                return ResourceManager.GetString("optionsExcludeEmptyRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to exclude from the registry scan.
        /// </summary>
        internal static string optionsExcludeFile {
            get {
                return ResourceManager.GetString("optionsExcludeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified registry key doesn&apos;t exist.
        /// </summary>
        internal static string optionsExcludeInvalidRegPath {
            get {
                return ResourceManager.GetString("optionsExcludeInvalidRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string optionsExcludeRemove {
            get {
                return ResourceManager.GetString("optionsExcludeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the backup files will be placed.
        /// </summary>
        internal static string optionsSelectBackupDir {
            get {
                return ResourceManager.GetString("optionsSelectBackupDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the log files will be placed.
        /// </summary>
        internal static string optionsSelectLogDir {
            get {
                return ResourceManager.GetString("optionsSelectLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another program seems to be running already....
        /// </summary>
        internal static string programAlreadyRunning {
            get {
                return ResourceManager.GetString("programAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an administrator to run this program.
        /// </summary>
        internal static string programNeedAdmin {
            get {
                return ResourceManager.GetString("programNeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &quot;Common Tools.dll&quot;.
        /// </summary>
        internal static string programNoCT {
            get {
                return ResourceManager.GetString("programNoCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string restoreAsk {
            get {
                return ResourceManager.GetString("restoreAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring registry.
        /// </summary>
        internal static string restoreError {
            get {
                return ResourceManager.GetString("restoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored registry.
        /// </summary>
        internal static string restoreRestored {
            get {
                return ResourceManager.GetString("restoreRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string scanDlgExit {
            get {
                return ResourceManager.GetString("scanDlgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning: .
        /// </summary>
        internal static string scanDlgProgressBarScanning {
            get {
                return ResourceManager.GetString("scanDlgProgressBarScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string updateLatest {
            get {
                return ResourceManager.GetString("updateLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version available.
        /// </summary>
        internal static string updateNewer {
            get {
                return ResourceManager.GetString("updateNewer", resourceCulture);
            }
        }
    }
}
