//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_Registry_Cleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Little_Registry_Cleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX/COM Objects.
        /// </summary>
        internal static string ActivexComObjects {
            get {
                return ResourceManager.GetString("ActivexComObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Info.
        /// </summary>
        internal static string ApplicationInfo {
            get {
                return ResourceManager.GetString("ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Paths.
        /// </summary>
        internal static string ApplicationPaths {
            get {
                return ResourceManager.GetString("ApplicationPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file or folder.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused File Extension.
        /// </summary>
        internal static string InvalidFileExt {
            get {
                return ResourceManager.GetString("InvalidFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find InprocServer.
        /// </summary>
        internal static string InvalidInprocServer {
            get {
                return ResourceManager.GetString("InvalidInprocServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find InprocServer32.
        /// </summary>
        internal static string InvalidInprocServer32 {
            get {
                return ResourceManager.GetString("InvalidInprocServer32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused ProgID/File Extension.
        /// </summary>
        internal static string InvalidProgIDFileExt {
            get {
                return ResourceManager.GetString("InvalidProgIDFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registry key.
        /// </summary>
        internal static string InvalidRegKey {
            get {
                return ResourceManager.GetString("InvalidRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar is invalid.
        /// </summary>
        internal static string InvalidToolbar {
            get {
                return ResourceManager.GetString("InvalidToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing AppID reference.
        /// </summary>
        internal static string MissingAppID {
            get {
                return ResourceManager.GetString("MissingAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing CLSID reference.
        /// </summary>
        internal static string MissingCLSID {
            get {
                return ResourceManager.GetString("MissingCLSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ProgID reference.
        /// </summary>
        internal static string MissingProgID {
            get {
                return ResourceManager.GetString("MissingProgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry key doesn&apos;t contain any data.
        /// </summary>
        internal static string NoRegKey {
            get {
                return ResourceManager.GetString("NoRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete registry key.
        /// </summary>
        internal static string ObsoleteRegKey {
            get {
                return ResourceManager.GetString("ObsoleteRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Documents.
        /// </summary>
        internal static string RecentDocs {
            get {
                return ResourceManager.GetString("RecentDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared DLLs.
        /// </summary>
        internal static string SharedDLLs {
            get {
                return ResourceManager.GetString("SharedDLLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Files.
        /// </summary>
        internal static string StartupFiles {
            get {
                return ResourceManager.GetString("StartupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Drivers.
        /// </summary>
        internal static string SystemDrivers {
            get {
                return ResourceManager.GetString("SystemDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Fonts.
        /// </summary>
        internal static string WindowsFonts {
            get {
                return ResourceManager.GetString("WindowsFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Help Files.
        /// </summary>
        internal static string WindowsHelpFiles {
            get {
                return ResourceManager.GetString("WindowsHelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Sounds.
        /// </summary>
        internal static string WindowsSounds {
            get {
                return ResourceManager.GetString("WindowsSounds", resourceCulture);
            }
        }
    }
}
